version: 2.1

orbs:
  node: circleci/node@5.0.2
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - run:
          command: curl ${VERCEL_HOOK}
workflows:
  test:
    jobs:
      - node/test:
          version: '16.16'
          pkg-manager: npm
          run-command: test:ci
          test-results-for: jest
      - deploy:
          filters:
            branches:
              only:
                - dev
                - circleci-editor/867/dev
          requires:
            - node/test
